### ISSUE TITLE
TypeError probably due to some bug in RandomClassRotation

### ISSUE THREAD

**Issue by ggbioing** [learnables/learn2learn#100]
https://github.com/learnables/learn2learn/blob/22dfb50aa5557162919f361f24df8353ec3441e4/examples/vision/maml_omniglot.py#L82

After having instantiated the train_tasks TaskDataset try to do:
```
for t in train_tasks:
    pass
```
At a random t I get the following error:
```
  File "/Software/Python3/miniconda3/envs/torch-1.4/lib/python3.7/site-packages/PIL/Image.py", line 2544, in new
    return im._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)

**Comment by seba-1511** [comment]
Thanks a lot for reporting this issue, and the other ones too.

Regarding the RandomClassRotation, which version of torchvision are you using ? With torch==1.3.1 and torchvision==0.4.2 I believe all of our tests were passing. It seems like what you're observing is related to the following bug, which was introduced with 0.5.0 and will be fixed in the upcoming version: https://github.com/pytorch/vision/issues/1759

For reference, I believe this is also why our tests are not passing lately.

**Comment by ggbioing** [comment]
torch=1.4.0; torchvision=0.5.0.
Changing:
https://github.com/learnables/learn2learn/blob/22dfb50aa5557162919f361f24df8353ec3441e4/learn2learn/vision/transforms.py#L47
to `transforms.RandomRotation((rot, rot), fill=(0,)),` does the job
