### ISSUE TITLE
MAML with RL

### ISSUE THREAD

**Issue by BillyCX** [learnables/learn2learn#101]
Hi,
In your given rl+maml example,  we always update the maml loss by using a2c.policyloss, even in the maml+ppo? I'm confused about it. Could you explain the reasons?
Meanwhile, in the meta rl examples, we only update the policy loss rather than value loss. I wonder do we also need to update the value loss(i.e. state loss) as well?
 
Thanks for your time.

**Comment by seba-1511** [comment]
Hello @BillyCX ,

Sorry for the delay, here're the answers to your questions:

1. Correct, we use the A2C loss (i.e. policy gradients) for fast-adaptation, and PPO/TRPO to optimize over the meta-updates of the parameters. The reason is mostly for efficiency/ease of implementation and is standard among RL implementations of MAML. I think you could easily give a shot to PPO for fast-adaptation, although the rigor of the approach is not clear to me nor whether you'd see a benefit. (c.f. DiCE and ProMP papers.)

2. We don't use a value loss because the value function is linear and we `.fit()` it to the rollouts data instead.

Hope this helps!
