### ISSUE TITLE
issue with downloading data

### ISSUE THREAD

**Issue by MichalisLazarou** [learnables/learn2learn#102]
Hey guys,

I keep getting the following errors when I run the maml_miniimagenet.py example. I did not change anything on the code do you have any idea why that might be the case.

Downloading: ./data/mini-imagenet-cache-train.pkl
Download finished
Traceback (most recent call last):
  File "/home/michalislazarou/PhD/learn2learn/examples/vision/maml_miniimagenet.py", line 179, in <module>
    main()
  File "/home/michalislazarou/PhD/learn2learn/examples/vision/maml_miniimagenet.py", line 66, in main
    train_dataset = l2l.vision.datasets.MiniImagenet(root='./data', mode='train')
  File "/home/michalislazarou/PhD/learn2learn/learn2learn/vision/datasets/mini_imagenet.py", line 94, in __init__
    self.data = pickle.load(f)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 35778727: invalid start byte

**Comment by seba-1511** [comment]
Hi @MichalisLazarou and thanks for opening the issue.

I suspect that this is due to a failure when downloading the data. (We really should check the checksum, but don't do it yet.) Could you remove the `data/` folder and run the script again, please ? For reference, I've tried to [copy-paste the example in colab](https://colab.research.google.com/drive/1lKZd1MvpJVUMuERrALMkDvAyq3VAiNps) and it seems fine there.

**Comment by MichalisLazarou** [comment]
Hey @seba-1511 thanks for letting me know. It seems that the error disappears once I delete the folder or even if i reboot my PC (Ubuntu 18.04). I am unsure why it happens but at least deleting the data file everytime seems to be working, just a bit annoying to doing it. Thanks for the quick reply :)

**Comment by seba-1511** [comment]
Closing, as it looks like a local installation issue.
