### ISSUE TITLE
Adapting only a subset of parameters

### ISSUE THREAD

**Issue by timweiland** [learnables/learn2learn#234]
Hey,

as some research has shown, it might sometimes be beneficial to adapt only a subset of all parameters in the inner loop. For example ANIL only adapts the head of the network. 

Is there a convenient way to do this for different parameter subsets? I've seen the ANIL tutorial in the docs, and there the model is explicitly split into body and head, and the head is then wrapped with `l2l.algorithms.MAML`. I think it would be really useful to have, for example, an optional `fast_params` argument to `l2l.algorithms.MAML` (and maybe also MetaSGD and GBML?), and then only the parameters specified by the user would get adapted in the inner loop. This would be a nice parallel to `torch.optim.Optimizer`, where you can also specify which parameters get optimized. This argument could default to `None`, in which case everything happens as it does now (i.e., all parameters are adapted).

I've also seen that the algorithms support parameters with `requires_grad=False`, but from what I understand this will exclude them from not only the inner loop but also the outer loop.

If this is a desirable feature, I could give it a shot at least for MAML. Or maybe there is already a way to do this and I just don't know about it :)

**Comment by seba-1511** [comment]
Hello @timweiland ,

That's a good feature request and I think it would be valuable to have a simple way to do it in the library. Here are some thoughts:

1. Although not documented, we have a [l2l.optim.transforms.TransformDictionary](https://github.com/learnables/learn2learn/blob/master/learn2learn/optim/transforms/transform_dictionary.py#L6) which can be used together with `l2l.algorithms.GBML` to achieve what you want. For example ANIL becomes:

~~~python
import torch
import learn2learn as l2l
from learn2learn.optim.transforms.transform_dictionary import TransformDictionary

model = l2l.vision.models.CNN4(5)
no_adapt = l2l.nn.Lambda(lambda grad: torch.zeros(1))
grad_adapt = l2l.nn.Lambda(lambda grad: grad)
transform = TransformDictionary({
    model.features: lambda param: no_adapt,  # on entire modules
    model.classifier.weight: lambda param: grad_adapt,  # on specific parameters
    model.classifier.bias: lambda param: grad_adapt,
})
anil = l2l.algorithms.GBML(model, transform=transform, lr=1.0)
img = torch.randn(5, 3, 84, 84)

learner = anil.clone()
out = learner(img)
learner.adapt(out.norm())

for (name, pre), (name, post) in zip(anil.named_parameters(), learner.named_parameters()):
    print(name, 'is adapted:', torch.norm(pre - post).item() > 1e-6)
~~~

2. Admittedly, the above is tedious and needs some ironing out and docs. But the `GBML` interface is quite powerful already and my plan is to build more tools "around" it (like better transforms, update rules, etc...) rather than "in" it (like more options).
3. If you were to implement the `fast_parameters` argument, I'd only bother with `MAML` and `GBML` (I'm slowly retiring Meta-SGD in favor of GBML). The only tricky part should be implementing `.clone()`: you'd have to keep track of the `fast_parameters`' clones and then pass them to the new `MAML/GBML` module.

I'm curious to hear opinions on combining `transforms` and `GBML` because so far I think I'm the only one who's needed to use them. Also, feel free to join [our slack](http://slack.learn2learn.net) for more timely replies.

**Comment by seba-1511** [comment]
Closing, discussed on slack.

**Comment by nightlessbaron** [comment]
Hi @seba-1511, thanks for this. It is an amazing functionality. `GBML` is indeed quite powerful!
I had a small doubt regarding the `GBML` wrapper. When we wrap the model around the `GBML` wrapper and `.clone()` it, the weights and biases present in the clone are no longer Parameters but are simply tensors. Thus, when I pass something like this to the `TransformDictionary`:
```python
transform = TransformDictionary({
    learner.module.classifier.weight: lambda param: no_adapt, 
    learner.module.classifier.bias: lambda param: grad_adapt
})
```
it results in `ValueError: TransformDictionary only accepts Modules or Parameters as dictionary keys.`, because now the `classifier.weight` is no longer a `nn.Parameter` but a tensor.

I had two questions:
1. Why is it no longer a `nn.Parameter`?
2. If we do want to feed `TransformDictionary` tensor value, how do we do it?

Thank you!
