### ISSUE TITLE
Why is recursion required in maml_update and clone_module

### ISSUE THREAD

**Issue by shivamsaboo17** [learnables/learn2learn#74]
I am a bit confused in the implementation of maml_update and clone_module function. In maml_update first the gradient update is done for all parameters of model. Doesn't this mean that all submodules are also updated because model.parameters will return all parameters? What is need of recursively again applying gradient update on submodules? I might be thinking in wrong direction hence would be very helpful if you can make this a bit more clear to me.

Best regards,
Shivam Saboo

**Comment by seba-1511** [comment]
Hello @shivamsaboo17 ,

The reason is that both `maml_update` and `clone_module` actually work at the module level. (We're only looping over the parameters of that particular module, not its children.) So once we're done with the parameters of the module, we have to recurse to also update/clone the parameters of the module's children.

Hope this clarifies stuff for you,
- Séb

**Comment by shivamsaboo17** [comment]
Thanks for clarifying. Indeed the modules will have to be recursively updated for submodules.
Closing the issue.

**Comment by gsygsygsy123** [comment]
I still confused about that why we should edit the parameters of module's children. In maml_update first the gradient update is done for all parameters of model.
