### ISSUE TITLE
cross domain example

### ISSUE THREAD

**Issue by vainaijr** [learnables/learn2learn#84]
hello,
how to train on mnist test on another dataset, that is cross domain, not testing on mnist dataset.

**Comment by seba-1511** [comment]
To train on MNIST, you can use [this script](https://github.com/learnables/learn2learn/blob/master/examples/vision/maml_omniglot.py), replacing Omniglot for MNIST and saving the weights at the end of training. To test on an other dataset, you could load those weights and use a similar script to the above, where instead of MNIST you use your dataset and remove lines 112 and 157.
